[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
data = { path = "../data" }
uuid = { workspace = true }
shipyard = { workspace = true }
protocol_proc = { path = "protocol_proc" }